sudo: required

language: generic

before_install:
- echo "start creating an image with dockerfile"
- docker build - t ymj3539/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true ymj3539/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"  
